### ISSUE TITLE
No Fulltext search

### ISSUE THREAD

**Issue by ibaxx** [Alfresco/alfresco-mobile-workspace-android#12]
Hi,

I have tried out the Workspace App from Google Play...
Sadly the search is only looking for filenames, not for fulltext info.

**Comment by agologan** [comment]
We search the name, title, description, the full text (if available) and tags.
You can look up the details here: [SeachApi.kt](https://github.com/Alfresco/alfresco-android-kotlin-api/blob/main/content-ktx/src/main/kotlin/com/alfresco/content/apis/SearchApi.kt)
Please keep in mind you can only search in docs supported by the transform service: https://docs.alfresco.com/content-services/latest/admin/transformations/#standard

**Comment by ibaxx** [comment]
then it is an Bug... on the old content android app it works... on the aca mobile website ist works...
but workspace app only delivers title matches.

**Comment by agologan** [comment]
Having just tested this I can confirm the functionality works.

Having said that maybe our expectations are different, so please provide screenshots, reproduction steps, a more comprehensive description of your expectation and maybe a sample document for us to test with.

_Reopening and marking as bug._

**Comment by ibaxx** [comment]
Hi, here are the screens... 13 matches on web app... 2 on android app

![NOTABLE-00003](https://user-images.githubusercontent.com/2786557/112341311-99b0a700-8cc1-11eb-9d28-efb3d713ea07.jpg)
![Screenshot_20210324-164335](https://user-images.githubusercontent.com/2786557/112341314-9a493d80-8cc1-11eb-83e9-4dd1258cb0ee.png)

**Comment by agologan** [comment]
We actually expect some results to differ compared to ACA as our search query has been adjusted to match Share which provides more accurate results.

Do your documents actually contain the search term?
Do you mind comparing your results to Share?

**Comment by ibaxx** [comment]
Hi Alexandru,

I have compared the results.
On my alfresco setup I have a library of cooking recipes, many in spanisch language.
I have used tomate (spanish tomato) as search term. 
With the aca website i got 108 results.
On share I got 106 results.

With the app I got only the 13 documents with the word in the title.
All files are PDFs.

![alfresco content](https://user-images.githubusercontent.com/2786557/112437635-716b8b80-8d47-11eb-848c-83dc6a085b3c.png)
![2021-03-25 08_45_17-Alfresco » Suche](https://user-images.githubusercontent.com/2786557/112437637-72042200-8d47-11eb-9654-5fae10fc33cb.png)

and finally all results of the app:
![Screenshot_20210325-084248](https://user-images.githubusercontent.com/2786557/112437776-995aef00-8d47-11eb-9566-646f5fe5a425.png)
![Screenshot_20210325-084311](https://user-images.githubusercontent.com/2786557/112437778-99f38580-8d47-11eb-9b7a-3f3cc8dbda55.png)
![Screenshot_20210325-084324](https://user-images.githubusercontent.com/2786557/112437780-9a8c1c00-8d47-11eb-8262-356e99d12c9f.png)

**Comment by agologan** [comment]
Thank you for providing access to your data.
After some testing I can confirm this issue is related to localization.
We already have an internal bug opened, and will get back to you once I know more.

If you switch your browser to English you'll notice the search results match across platforms but your results no longer include the textual matches.

**Comment by ibaxx** [comment]
#response_container_BBPPID{font-family: initial; font-size:initial; color: initial;}  Thank you for stay me informed.Would that mean, maybe other issues with special German characters i had noticed in the past could be, because the server is German localized?                                                                                                                                                                                                                                                                                                                        Von: ***@***.***Gesendet: 25. März 2021 18:32An: ***@***.***Antworten: ***@***.***Cc: ***@***.***; ***@***.***Betreff: Re: [Alfresco/alfresco-mobile-workspace-android] No Fulltext search (#12)  
Thank you for providing access to your data.
After some testing I can confirm this issue is related to localization.
We already have an internal bug opened, and will get back to you once I know more.
If you switch your browser to English you'll notice the search results match across platforms but your results no longer include the textual matches.

—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by agologan** [comment]
Maybe, you'd need to report the individual issues on the separate products for investigation which we encourage you to do.

**Comment by agologan** [comment]
For a more complete picture could you please provide the following:
- version of your Content Services deployment
- search engine information (from your **admin** console head over to **Repository Services** / **Search Service** and provide which **Search Service** you're using and **Full Text Search** config (bottom of the page))

**Comment by agologan** [comment]
Having spoken to one of colleagues in search it seems the problem stems from your data being indexed in another language.
This can be resolved by enabling cross language searches: **Step 3** in this guide https://docs.alfresco.com/search-services/latest/install/options/

> 3. If you use several languages across your organization, you must enable cross-language search support in all fields. To do > this update the alfresco-search-services/solrhome/conf/shared.properties file:
```
 alfresco.cross.locale.datatype.0={http://www.alfresco.org/model/dictionary/1.0}text
 alfresco.cross.locale.datatype.1={http://www.alfresco.org/model/dictionary/1.0}content
 alfresco.cross.locale.datatype.2={http://www.alfresco.org/model/dictionary/1.0}mltext
```

**Comment by ibaxx** [comment]
Hi Alexandru,

it looks like, that this helps.
But why isn't this feature enabled by default?

I think all Setups will have more than one language in their documents.

Regards
Ingo

**Comment by agologan** [comment]
It's a good question that I already plan to discuss with the team.

_For now marking this as resolved. Thank you for your patience._
